language: php
php:
  - 7.2
  - 7.3
notifications:
  email:false
branches:
  only:
  - master
  - travis
install:
  - COMPOSER_VENDOR_DIR=vendors composer require --prefer-dist simpletest/simpletest "^1.0"
script: cd app && ../cake/console/cake testsuite core all
