language: php
php:
  - 7.2
  - 7.3
notifications:
  email:false
branches:
  only:
  - master
  - travis
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - echo "<?php\nclass DATABASE_CONFIG {\nvar $test = array('driver' => 'mysql', 'persistent' => false, 'host' => '127.0.0.1', 'login' => 'travis', 'password' => '', 'database' => 'test', 'prefix' => '',););\n}" > ./app/config/database.php
script: cd app && ../cake/console/cake testsuite core all
