language: php
php:
  - 7.2
  - 7.3
notifications:
  email:false
branches:
  only:
  - master
  - travis
install:
  - composer require --prefer-dist simpletest/simpletest "^1.0"
script: cd app && cake testsuite core all
