language: php
php:
  - 7.2
notifications:
  email:false
branches:
  only:
  - travis
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - echo "<?php class DATABASE_CONFIG { var \$test = array('driver' => 'mysqli', 'persistent' => false, 'host' => '127.0.0.1', 'login' => 'travis', 'password' => '', 'database' => 'test', 'prefix' => '',);}" > ./app/config/database.php
script:
  - cd app && ../cake/console/cake testsuite core all
